knife4j:
  enable: true
  openapi:
    title: 用户中心
    description: 用户中心接口文档
    email: 903586678@qq.com
    concat: 林泽源
    url: https://docs.xiaominfo.com
    version: v0.0.1
    group:
      user-controller:
        group-name: 用户模块
        api-rule: package
        api-rule-resources:
          - org.example.peermatch.controller